const instanceList = [
  "https://invidious.baczek.me",
  "https://vid.puffyan.us",
  "https://inv.riverside.rocks",
  "https://yewtu.be",
  "https://invidious.kavin.rocks",
  "https://watch.thekitty.zone",
  "https://y.com.sb",
  "https://invidious.nerdvpn.de",
  "https://invidious.tiekoetter.com",
  "https://yt.artemislena.eu",
  "https://invidious.flokinet.to",
  "https://inv.bp.projectsegfau.lt",
  "https://inv.odyssey346.dev",
  "https://invidious.sethforprivacy.com",
  "https://invidious.snopyta.org",
  "https://yt.funami.tech",
  "https://invidious.epicsite.xyz",
  "https://iv.ggtyler.dev",
  "https://inv.vern.cc",
  "https://yt.oelrichsgarcia.de",
  "https://invidious.silur.me",
  "https://invidious.slipfox.xyz",
  "https://invidious.weblibre.org",
  "https://invidious.esmailelbob.xyz",
  "https://iv.melmac.space",
  "https://invidious.dhusch.de",
  "https://invidious.privacydev.net",
  "https://invidious.lidarshield.cloud",
  "https://invidious.namazso.eu",
];

export { instanceList };
