DROP TABLE IF EXISTS videos CASCADE;
CREATE TABLE videos (
  id SERIAL PRIMARY KEY NOT NULL,
  yt_video_key VARCHAR(11) NOT NULL,
  title VARCHAR(255) NOT NULL,
  playlist_id INTEGER REFERENCES playlists(id) ON DELETE CASCADE
);